name: CI/CD Azure Frontier Girls Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Executar testes automatizados
        run: npm test

deliver: 
  needs: build_and_test
  runs-on: ubuntu-latest
  if : success()
  
  steps:
    - name: Simulação de entrega
      run: echo "Deploy simulado com Sucesso! (Continuous Delivery)"